"use client";

const PrintFooter = () => {
  return (
    <footer className="w-full border-t border-gray-300 text-[10px] text-gray-700 mt-4 pt-1">
      <div className="flex justify-between items-center">
        {/* Left */}
        <span>Generated by Passbook System</span>

        {/* Center */}
        <span>Authorized Computer Print</span>

        {/* Right */}
        <span>Page 1</span>
      </div>
    </footer>
  );
};

export default PrintFooter;
